name: CI & CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install and build library
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: library artifacts
          path: dist/
          
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with: 
        name: library artifacts
        path: dist
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: 
        npm test
      env:
        CI: true
    