name: CI & CD
on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build library
        run: |
          npm install --legacy-peer-deps
          npm run test
          npm run build
      - name: Build React App
        run: |
          cd example
          npm install --legacy-peer-deps
          npm run build
      - name: Deploy
        run: |
          ./node_modules/.bin/netlify deploy --prod dir=./example/build --site ${{secrets.netlify_site_id}} --auth ${{secrets.netlify_personal_access_token}}
