name: CI & CD
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        - run: npm run predeploy
        - run: npm deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}

