name: CI & CD
on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install & test & build
        run: |
          npm install
          # npm run build
          npm run test
      - name: Deploy
        # uses: crazy-max/ghaction-github-pages@v2
        # with:
        #   target_branch: gh-pages
        #   build_dir: ./example/build
        run: |
          git config --global user.email "frienda97.it@gmail.com"
          git config --global user.name "FriendA97"
          npm run deploy
        env:
          GH_PAT: ${{ secrets.EASY_PRINT_LIBRARY }}
