name: CI & CD
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
        run: |
          npm install
          npm run build
          npm run test
      - name: Deploy
        run: |
          npm run predeploy
          npm deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}

